# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 183fccf989a4b8533472e4b9588742361f43fd461a2bf6d28c8b8a5ffea85780532a87ff0c9b9a2efe3055063296308293a94b9397870138e33f14f049668241

test:
  secret_key_base: c9c242982a216e1ebba4df4260b94b05de6a3d3d9b1f2544b930368e38359691e259456ae0852e3e77c0742c2afbd173a51033990d1023ce0dea7c8cab2a0c8f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
